### ISSUE TITLE
Crash app with latest version

### ISSUE THREAD

**Issue by andre-sonect** [urbanairship/android-segment-integration#9]
I am getting this with latest version.

`Fatal Exception: java.lang.NoSuchMethodError: No virtual method create()Lcom/urbanairship/analytics/CustomEvent; in class Lcom/urbanairship/analytics/CustomEvent$Builder; or its super classes (declaration of 'com.urbanairship.analytics.CustomEvent$Builder' appears in /data/app/ch.sonect.app.dev-W1zjqAq8BudK2Zpkv-fqgw==/base.apk:classes3.dex) at com.urbanairship.extension.segment.UrbanAirshipIntegration.track(UrbanAirshipIntegration.java:100) at com.segment.analytics.IntegrationOperation$10.run(IntegrationOperation.java:228) at com.segment.analytics.Analytics.performRun(Analytics.java:1476) at com.segment.analytics.Analytics$10.run(Analytics.java:837) at android.os.Handler.handleCallback(Handler.java:808) at android.os.Handler.dispatchMessage(Handler.java:101) at android.os.Looper.loop(Looper.java:166) at android.app.ActivityThread.main(ActivityThread.java:7529) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)`

**Comment by rlepinski** [comment]
This plugin has yet to be updated to work with Airship SDK 10.0. Make sure you are still using 9.7.1. We will have an update in the next week or two.

**Comment by rlepinski** [comment]
2.0.0 is out that works with the latest Android SDK and AndroidX
